export type Grant = {
  id: string
  snapshot_id: string
  snapshot_space: string
  snapshot_proposal: {
    name: string
    body: string
    choices: any[]
    snapshot: number
    end: number
    start: number
    metadata: any
  }
  snapshot_signature: string
  snapshot_network: '1'
  discourse_id: number
  discourse_topic_id: number
  discourse_topic_slug: string
  user: string
  type: 'grant'
  status: string
  title: string
  description: string
  configuration: {
    title: string
    abstract: string
    category: string
    tier: string
    size: number
    beneficiary: string
    description: string
    specification: string
    personnel: string
    roadmap: string
    choices: any[]
    vestingStartDate: string
    projectDuration: number
    paymentToken: string
  }
  enacted: false
  enacted_description: null
  deleted: false
  start_at: string
  finish_at: string
  created_at: string
  updated_at: string
  enacted_by: null
  deleted_by: null
  required_to_pass: number
  passed_by: null
  passed_description: null
  rejected_by: null
  rejected_description: null
  vesting_address: null
  textsearch: string
  enacting_tx: null
}
